---
title: "R Notebook"
output: html_notebook
---

## Libraries

```{r}
library(dplyr)
library(tidyverse)
library(stringr)


library(usethis)
use_git_config(user.name = "malina-a", user.email = "malina.aniol@sciencespo.fr")

```


use "data/EES_aggregated_macrovariables.dta", clear

```{r}
load("C:/Users/malin/Downloads/EES_aggregated_macrovariables.RData")
a <- table
```

add macro-level variables
```{r}

a$presidential <- 0

a$presidential[a$country == 1 |a$country == 3 |a$country == 4|a$country == 10|a$country == 14|a$country == 17|a$country == 21|a$country == 22|a$country == 23] <- 1

a$presidential[a$country==6 & a$year>=2013] <- 1
a$presidential[a$country==24 & a$year>=1999] <- 1
a$presidential[a$country==25 & a$year<=2002] <- 1
a$presidential[a$country==25 & a$year>=2012] <- 1

# alternative dplyr version

# table <- table %>%
#   mutate(presidential = case_when(
#     country %in% c(1, 3, 4, 10, 14, 17, 21, 22, 23) ~ 1,
#     country == 6 & year >= 2013 ~ 1,
#     country == 24 & year >= 1999 ~ 1,
#     country == 25 & year <= 2002 ~ 1,
#     country == 25 & year >= 2012 ~ 1,
#     TRUE ~ 0  # default value
#   ))


a <- a |>
  mutate(legislative_type = case_when(
    country %in% c(3,4,11,19,12,13,15,17,23) ~ 1,
    country == 10 ~ 2,
    country == 28 ~2,
    country==3 & year==2009 ~ 2,
    country==4 & year<=1995 ~ 2,
    country==15 & year>=1994 & year <=2001 ~ 2,
    country==23 & year>=2008 & year<=2012 ~ 2,
    TRUE ~ 0
  ))

a <- a |>
  mutate(majoritarian = case_when(
    legislative_type ==1 ~ 0,
    legislative_type==2 ~ 1
  ))
  

```

** add math score data

```{r}

load("D:/Rep_R/Rep_Kostelka/maths_diff_to_merge.RData")
m <- table


a$countryyear <- paste(a$country,a$year, sep = "") # alternatively paste0

mmaths <- merge(a,m, by =c("country","year", "countryyear"))
# 
# 	merge m:1 countryyear using "data/maths_diff_to_merge.dta"
# 	drop if _merge==2
# 	drop _merge
```

